### PR TITLE
AWS Lambda Layers

### PR DESCRIPTION
**Pull request by jpappel**
Provides an additional implementation of the BingoMaker API, utilizing AWS Lambda functions. All lambdas share a common base layer.

### CODE REVIEW

**Comment by jpappel** [comment]
I think the initial scope of this PR was too large, I am changing it to only be for the creation and upload the lambda layers.

**Comment by jpappel** [comment]
Here is the documentation for creating lambdas using terraform
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function .

**Comment by jpappel** [comment]
Latest commit should resolve #45

**Review by yousufkanan — APPROVED** [review]
LGTM!

**Review by OnToNothing — APPROVED** [review]
Looks great!

**Pull request merged**
